// MapDB.cpp – full Trickster map table with image & tooltip placeholders
#include "MapDB.h"
#include <unordered_map>
#include <string>       //  ← NEW
#include <algorithm>    //  ← NEW
#include <cctype>       //  ← NEW

struct MapEntry { const char* name; const char* asset; const char* tip; };

using MapTable = std::unordered_map<int, MapEntry>;

/*───────────────────────────  FULL TABLE  ───────────────────────────*/

// {   1,  { "Megalopolis Square", "alteo", "Alteo Empire Area" } },


static const MapTable g_MapName = {
    {   0,  { "Intro", "unknown", "Unknown Map" } },
    {   1,  { "Megalopolis Square", "megalo", "Megalopolis Area" } },
    {  10,  { "Phantom School - 2F Chilly Hallway", "phantom", "Phantom School" } },
    { 100,  { "Tapasco Field 1 - Net of Lava", "tapasco", "Tapasco Volcano Area" } },
    { 101,  { "Tapasco Field 2 - Rhythm of Hammer", "tapasco", "Tapasco Volcano Area" } },
    { 102,  { "Tapasco Field 3 - Valley of Flame", "tapasco", "Tapasco Volcano Area" } },
    { 103,  { "Tapasco Field 4 - Stairway to Fire", "tapasco", "Tapasco Volcano Area" } },
    { 104,  { "Spicy Island", "tapasco", "Tapasco Volcano Area" } },
    { 105,  { "Vamp Dungeon 5 - Resurrection of Dark", "vamp", "Vamp Castle" } },
    { 106,  { "Vamp Dungeon 4 - Center of the Dark", "vamp", "Vamp Castle" } },
    { 107,  { "Vamp Dungeon 1 - Banquet of the Vamp", "vamp", "Vamp Castle" } },
    { 108,  { "Vamp Dungeon 2 - Banquet of the Dead", "vamp", "Vamp Castle" } },
    { 109,  { "Vamp Dungeon 3 - Song of Moonlight", "vamp", "Vamp Castle" } },
    {  11,  { "Swamp Field 1 - Black Hole", "swamp", "Swamp Area" } },
    { 110,  { "Secret Room of Rosetta", "rose", "Rose Garden Area" } },
    { 111,  { "Phantom School - 1F Silent Hallway", "phantom", "Phantom School" } },
    { 112,  { "Phantom School 1-1", "phantom", "Phantom School" } },
    { 113,  { "Phantom School 1-2", "phantom", "Phantom School" } },
    { 114,  { "Phantom School 1-3", "phantom", "Phantom School" } },
    { 115,  { "Phantom School 1-4", "phantom", "Phantom School" } },
    { 116,  { "Gate of Phantom School", "phantom", "Phantom School" } },
    { 117,  { "Path to Phantom School", "phantom", "Phantom School" } },
    { 118,  { "Swamp Dungeon 1 - Marshy Trail", "swampdungeon", "Swamp Dungeon" } },
    { 119,  { "Swamp Dungeon 2 - Marshy Pool", "swampdungeon", "Swamp Dungeon" } },
    {  12,  { "Desert Beach Field 2 - Sand Palace", "desert", "Desert Beach Area" } },
    { 120,  { "Swamp Dungeon 3 - Marshy vacant lot", "swampdungeon", "Swamp Dungeon" } },
    { 121,  { "Swamp Dungeon 4 - Marshy Garden", "swampdungeon", "Swamp Dungeon" } },
    { 122,  { "Swamp Dungeon 5 - Marshy Lawn", "swampdungeon", "Swamp Dungeon" } },
    { 123,  { "Swamp Dungeon 6 - Suu's Muddy pool", "swampdungeon", "Swamp Dungeon" } },
    { 124,  { "Phantom School - 1F Toilet", "phantom", "Phantom School" } },
    { 125,  { "Phantom School 2-1", "phantom", "Phantom School" } },
    { 126,  { "Phantom School 2-2", "phantom", "Phantom School" } },
    { 127,  { "Phantom School 2-3", "phantom", "Phantom School" } },
    { 128,  { "Phantom School 2-4", "phantom", "Phantom School" } },
    { 129,  { "Phantom School - 2F Toilet", "phantom", "Phantom School" } },
    {  13,  { "Desert Beach Field 3 - Statue of Anubis", "desert", "Desert Beach Area" } },
    { 130,  { "Phantom School - 3F Shiver Hallway", "phantom", "Phantom School" } },
    { 131,  { "Phantom School 3-1", "phantom", "Phantom School" } },
    { 132,  { "Phantom School 3-2", "phantom", "Phantom School" } },
    { 133,  { "Phantom School 3-3", "phantom", "Phantom School" } },
    { 134,  { "Phantom School 3-4", "phantom", "Phantom School" } },
    { 135,  { "Phantom School - 3F Toilet", "phantom", "Phantom School" } },
    { 136,  { "Beginner's Square - Training Camp", "unknown", "Unknown Map" } },
    { 137,  { "Beginner's Square - Monster Guild", "unknown", "Unknown Map" } },
    { 138,  { "Beginner's Square - Skill Shrine", "unknown", "Unknown Map" } },
    { 139,  { "Beginner's Square - Training Garden1", "unknown", "Unknown Map" } },
    {  14,  { "Swamp Field 2 - Beaver's Swamp", "swamp", "Swamp Area" } },
    { 140,  { "Beginner's Square - Training Garden2", "unknown", "Unknown Map" } },
    { 141,  { "Phantom School Annex - 2F Hallway", "phantom", "Phantom School" } },
    { 142,  { "Phantom School - Music Room", "phantom", "Phantom School" } },
    { 143,  { "Phantom School - Art Room", "phantom", "Phantom School" } },
    { 144,  { "Phantom Snack Bar", "phantom", "Phantom School" } },
    { 145,  { "Lost Land 6", "unknown", "Unknown Map" }  },
    { 146,  { "Path to Techichi 1 - Sleet Forest", "techichi", "Techichi Volcano Area" } },
    { 147,  { "Path to Techichi 2 - Dry Forest", "techichi", "Techichi Volcano Area" } },
    { 148,  { "Coral Town - Blooming Cora", "cora", "Coral Beach Area" } },
    { 149,  { "Lost Land 1", "unknown", "Unknown Map" }  },
    {  15,  { "Swamp Field 3 - Maze of Forest", "swamp", "Swamp Area" } },
    { 150,  { "Lost Land 2", "unknown", "Unknown Map" }  },
    { 151,  { "Lost Land 3", "unknown", "Unknown Map" }  },
    { 152,  { "Coral Beach - Dark Cave", "cave", "Coral Beach Area" } },
    { 153,  { "Coral Beach Field 1 - Blue Wave", "cora", "Coral Beach Area" } },
    { 154,  { "Coral Beach Field 2 - Passionate Sun", "cora", "Coral Beach Area" } },
    { 155,  { "Coral Beach Field 3 - Sunny Beach", "cora", "Coral Beach Area" } },
    { 157,  { "Blooming Cora Shop", "cora", "Coral Beach Area" } },
    { 159,  { "Gate of Poppuri Dungeon", "poppuri", "Poppuri Dungeon" } },
    {  16,  { "Southeast Forest", "megalo", "Megalopolis Area" } },
    { 160,  { "Poppuri Dungeon - Slide Cave", "poppuri", "Poppuri Dungeon" } },
    { 161,  { "Poppuri Dungeon - Rainbow Cave", "poppuri", "Poppuri Dungeon" } },
    { 162,  { "Poppuri Dungeon - Moss Cave", "poppuri", "Poppuri Dungeon" } },
    { 163,  { "Poppuri Dungeon - Spore Cave", "poppuri", "Poppuri Dungeon" } },
    { 164,  { "Poppuri Dungeon - Root Cave", "poppuri", "Poppuri Dungeon" } },
    { 165,  { "Phantom School Annex - 1F Hallway", "phantom", "Phantom School" } },
    { 166,  { "Phantom School - Machinery Room", "phantom", "Phantom School" } },
    { 167,  { "Phantom School - Science Lab", "phantom", "Phantom School" } },
    { 168,  { "Gate of Vamp Castle", "vamp", "Vamp Castle" } },
    { 169,  { "Gate of Snow Hill", "snow", "Snow Hill Area" } },
    {  17,  { "Southwest Forest", "megalo", "Megalopolis Area" } },
    { 170,  { "Gate of Blue Ice Dungeon", "icedungeon", "Ice Dungeon" } },
    { 171,  { "Gate of Techichi", "techichi", "Techichi Volcano Area" } },
    { 172,  { "Path to Phantom School Annex", "phantom", "Phantom School" } },
    { 174,  { "Wharf Field 1 - Haunted Town", "oops", "Oops Wharf" } },
    { 175,  { "Wharf Field 2 - Devil Crow", "oops", "Oops Wharf" } },
    { 176,  { "Wharf Field 3 - Phantom Park", "oops", "Oops Wharf" } },
    { 177,  { "Wharf Field 4 - Chrono Wharf", "oops", "Oops Wharf" } },
    { 178,  { "Guild Colosseum Lobby", "event", "Event Garden" } },
    { 179,  { "Cave Arena", "event", "Event Garden" } },
    {  18,  { "Northwest Forest", "megalo", "Megalopolis Area" } },
    { 180,  { "Ball Room 5 - Jelly Alert", "unknown", "Unknown Map" } },
    { 181,  { "Ball Room 3 - Cucool Alert", "unknown", "Unknown Map" } },
    { 182,  { "Ball Room 6 - Mask Alert", "unknown", "Unknown Map" } },
    { 183,  { "Garden of Skill Master", "megalo", "Megalopolis Area" } },
    { 184,  { "First Room of Job Administrators", "unknown", "Unknown Map" }  },
    { 185,  { "Second Room of Job Administrators", "unknown", "Unknown Map" }  },
    { 186,  { "Colosseum Waiting room", "event", "Event Garden" } },
    { 187,  { "First Battlefield - Battlefield of Desert", "event", "Event Garden" } },
    { 188,  { "Second Battlefield - Battlefield of Garden", "event", "Event Garden" } },
    { 189,  { "Phantom Arena", "phantom", "Phantom School" } },
    {  19,  { "Path to Desert Beach", "desert", "Desert Beach Area" } },
    { 190,  { "Inferno Arena", "event", "Event Garden Area" } },
    { 191,  { "Pirate King Karan's Room", "ghost", "Ghost Blue Area" } },
    { 192,  { "Pyramid Dungeon 7 - Doom of Pharaoh", "pyramid", "Pyramid Dungeon" } },
    { 193,  { "Event Zone 4 - Baldy", "unknown", "Unknown Map" } },
    { 194,  { "Ball Room 8 - Snow Lady Alert", "snow", "Snow Hill Area" } },
    { 195,  { "Third Battlefield - Battlefield of Duel", "event", "Event Garden" } },
    { 196,  { "1st Mining Lot of Crystal Copper", "mine", "Mines" } },
    { 197,  { "1st Mining Lot of Jade Steel", "mine", "Mines" } },
    { 198,  { "1st Mining Lot of Silver Jewel", "mine", "Mines" } },
    { 199,  { "1st Mining Lot of Precious Jewel", "mine", "Mines" } },
    {   2,  { "Gate of Caballa Relics", "cabala", "Caballa Relics Area" } },
    {  20,  { "Path to Ghost Blue 1", "ghost", "Ghost Blue Area" } },
    { 200,  { "Swamp Dungeon7 - Tenterlion's Cave", "swampdungeon", "Swamp Dungeon" } },
    { 201,  { "Spicy Dragon Lair", "tapasco", "Tapasco Volcano Area" } },
    { 202,  { "Desert Beach Mine - Crystal Copper", "mine", "Mines" } },
    { 203,  { "Caballa Relics Mine - Jade Steel", "mine", "Mines" } },
    { 204,  { "Swamp Mine - Silver Jewel", "mine", "Mines" } },
    { 205,  { "Snow Mine - Precious Jewel", "mine", "Mines" } },
    { 206,  { "2nd Mining Lot of Crystal Copper", "mine", "Mines" } },
    { 207,  { "2nd Mining Lot of Jade Steel", "mine", "Mines" } },
    { 208,  { "2nd Mining Lot of Silver Jewel", "mine", "Mines" } },
    { 209,  { "2nd Mining Lot of Precious Jewel", "mine", "Mines" } },
    {  21,  { "Path to Caballa Relics", "cabala", "Caballa Relics Area" } },
    { 210,  { "Ice Dungeon 5 - Room of Odinea", "icedungeon", "Ice Dungeon" } },
    { 211,  { "Vamp Castle Boss Room", "vamp", "Vamp Castle" } },
    { 212,  { "Nora's Arena", "nora", "Nora Sewer" } },
    { 213,  { "Inferno Arena M", "event", "Event Garden Area" } },
    { 214,  { "Wharf Field - Boss Room", "oops", "Oops Wharf" } },
    { 215,  { "Phantom School - Mad Ray's Lab", "phantom", "Phantom School" } },
    { 216,  { "Coral Beach - Master Mong's Lair", "cora", "Coral Beach Area" } },
    { 217,  { "Soki's Hamlet", "ash", "Black Ash Dungeon" } },
    { 218,  { "Event Garden OX", "event", "Event Garden" } },
    { 219,  { "Mermaid Palace Field 1 - Water Park", "mermaid", "Mermaid Palace Area" } },
    {  22,  { "Path to Black Swamp", "swamp", "Swamp Area" } },
    { 220,  { "Mermaid Palace Field 2 - Seaweeds Square", "mermaid", "Mermaid Palace Area" } },
    { 221,  { "Mermaid Palace Field 3 - Coral Square", "mermaid", "Mermaid Palace Area" } },
    { 222,  { "Mermaid Palace Field 4 - Rock Square", "mermaid", "Mermaid Palace Area" } },
    { 223,  { "Ice Prison", "icedungeon", "Ice Dungeon" } },
    { 224,  { "Ice Prison", "icedungeon", "Ice Dungeon" } },
    { 225,  { "Ice Prison", "icedungeon", "Ice Dungeon" } },
    { 226,  { "Ice Prison", "icedungeon", "Ice Dungeon" } },
    { 227,  { "Ice Prison", "icedungeon", "Ice Dungeon" } },
    {  23,  { "Path to Oops Wharf", "oops", "Oops Wharf" } },
    { 232,  { "Cherry Blossom 1", "cherry", "Cherry Blossom" } },
    { 233,  { "Cherry Blossom", "cherry", "Cherry Blossom" } },
    { 236,  { "Soccer Arena", "event", "Event Garden" } },
    { 238,  { "One Way Arena", "event", "Event Garden Area" } },
    { 239,  { "Room of Guardian", "megalo", "Megalopolis Area" } },
    {  24,  { "Frost Wind Forest 1", "megalo", "Megalopolis Area" } },
    { 240,  { "Room of Guardian", "megalo", "Megalopolis Area" } },
    { 241,  { "Room of Guardian", "megalo", "Megalopolis Area" } },
    { 242,  { "Room of Guardian", "megalo", "Megalopolis Area" } },
    { 243,  { "Room of Guardian", "megalo", "Megalopolis Area" } },
    { 244,  { "Room of Guardian", "megalo", "Megalopolis Area" } },
    { 245,  { "Room of Guardian", "megalo", "Megalopolis Area" } },
    { 246,  { "Room of Guardian", "megalo", "Megalopolis Area" } },
    { 247,  { "Room of Tribulation - 1", "megalo", "Megalopolis Area" } },
    { 248,  { "Room of Tribulation - 2", "megalo", "Megalopolis Area" } },
    { 249,  { "Room of Tribulation - 3", "megalo", "Megalopolis Area" } },
    {  25,  { "Relics Field 2 - Hand of Giant", "cabala", "Caballa Relics Area" } },
    { 250,  { "Room of Tribulation - 4", "megalo", "Megalopolis Area" } },
    { 251,  { "Room of Tribulation - 5", "megalo", "Megalopolis Area" } },
    { 252,  { "Room of Tribulation - 6", "megalo", "Megalopolis Area" } },
    { 253,  { "Room of Tribulation - 7", "megalo", "Megalopolis Area" } },
    { 254,  { "Room of Tribulation - 8", "megalo", "Megalopolis Area" } },
    { 255,  { "Room of Tribulation - 9", "megalo", "Megalopolis Area" } },
    { 256,  { "Room of Tribulation - 10", "megalo", "Megalopolis Area" } },
    { 257,  { "Room of Tribulation - 11", "megalo", "Megalopolis Area" } },
    { 258,  { "Room of Tribulation - 12", "megalo", "Megalopolis Area" } },
    { 259,  { "Room of Tribulation - 13", "megalo", "Megalopolis Area" } },
    {  26,  { "Relics Field 3 - Monkey Statues", "cabala", "Caballa Relics Area" } },
    { 260,  { "Room of Tribulation - 14", "megalo", "Megalopolis Area" } },
    { 261,  { "Room of Tribulation - 15", "megalo", "Megalopolis Area" } },
    { 262,  { "Room of Tribulation - 16", "megalo", "Megalopolis Area" } },
    { 263,  { "Black Ash Dungeon 1", "ash", "Black Ash Dungeon" } },
    { 264,  { "Black Ash Dungeon 2", "ash", "Black Ash Dungeon" } },
    { 265,  { "Black Ash Dungeon 3", "ash", "Black Ash Dungeon" } },
    { 266,  { "Black Ash Dungeon 4", "ash", "Black Ash Dungeon" } },
    { 267,  { "Gate of Mermaid Dungeon", "mermaiddungeon", "Mermaid Dungeon" } },
    { 268,  { "Mermaid Dungeon 1 - Underworld", "mermaiddungeon", "Mermaid Dungeon" } },
    { 269,  { "Mermaid Dungeon 2 - Legend of the sea", "mermaiddungeon", "Mermaid Dungeon" } },
    {  27,  { "Seabed Field 1 - North", "ghost", "Ghost Blue Area" } },
    { 270,  { "Gate to Mirage Island", "mirage", "Mirage Island Area" } },
    { 271,  { "Mirage Island Field 1 - Alteo", "mirage", "Mirage Island Area" } },
    { 272,  { "Mirage Island Field 2 - Cliff of Fate", "mirage", "Mirage Island Area" } },
    { 273,  { "Mirage Island Field 3 - Fremeia", "mirage", "Mirage Island Area" } },
    { 274,  { "Mirage Island Dungeon 1 - Ocean's End", "cave", "Mirage Island Area" } },
    { 275,  { "Mirage Island Dungeon 2 - Deepest Cave", "cave", "Mirage Island Area" } },
    { 276,  { "Don Guivanni's Secret Room", "dev", "Underground Dev Area" } },
    { 277,  { "Room of Guardian - Test of Calmness", "pyramid", "Pyramid Dungeon" } },
    { 278,  { "Room of Guardian - Test of Quickness", "pyramid", "Pyramid Dungeon" } },
    { 279,  { "Room of Guardian - Test of Knowledge", "pyramid", "Pyramid Dungeon" } },
    {  28,  { "Seabed Field 2 - East", "ghost", "Ghost Blue Area" } },
    { 280,  { "Room of Guardian - Test of Knowledge", "pyramid", "Pyramid Dungeon" } },
    { 281,  { "Room of Guardian - Test of Power", "pyramid", "Pyramid Dungeon" } },
    { 282,  { "Room of Truth", "pyramid", "Pyramid Dungeon" } },
    { 283,  { "Room of Truth", "pyramid", "Pyramid Dungeon" } },
    { 284,  { "Gate of Oops Wharf", "oops", "Oops Wharf" } },
    { 285,  { "Path to Mermaid Palace 1", "mermaid", "Mermaid Palace Area" } },
    { 286,  { "Path to Mermaid Palace 2", "mermaid", "Mermaid Palace Area" } },
    { 288,  { "The Witch's Dungeon", "unknown", "Unknown Map" } },
    { 289,  { "Hologram Room", "unknown", "Unknown Map" } },
    {  29,  { "Path to Ghost Blue 2", "ghost", "Ghost Blue Area" } },
    { 290,  { "棒球場", "unknown", "Unknown Map" } },
    { 291,  { "Nate's Lab", "unknown", "Unknown Map" } },
    { 292,  { "Ball Room 4  - Skull Alert", "unknown", "Unknown Map" } },
    { 293,  { "Halloween Square", "unknown", "Unknown Map" } },
    { 294,  { "Halloween Field 1", "unknown", "Unknown Map" } },
    { 295,  { "Halloween Field 2", "unknown", "Unknown Map" } },
    { 296,  { "1st Closed Lot of Crystal Copper", "mine", "Mines" } },
    { 297,  { "2nd Closed Lot of Crystal Copper", "mine", "Mines" } },
    { 298,  { "1st Closed Lot of Jade Steel", "mine", "Mines" } },
    { 299,  { "2nd Closed Lot of Jade Steel", "mine", "Mines" } },
    {   3,  { "Gate of Desert Beach", "desert", "Desert Beach Area" } },
    {  30,  { "Beach Field 4 - Parasol River", "desert", "Desert Beach Area" } },
    { 300,  { "1st Closed Lot of Silver Jewel", "mine", "Mines" } },
    { 301,  { "2nd Closed Lot of Silver Jewel", "mine", "Mines" } },
    { 302,  { "1st Closed Lot of Precious Jewel", "mine", "Mines" } },
    { 303,  { "2nd Closed Lot of Precious Jewel", "mine", "Mines" } },
    { 304,  { "Vamp Castle Boss Room 1 - Lower Gate", "vamp", "Vamp Castle" } },
    { 305,  { "Vamp Castle Boss Room 2 - Sacrifice", "vamp", "Vamp Castle" } },
    { 306,  { "Vamp Castle Boss Room 3 - Wisdom", "vamp", "Vamp Castle" } },
    { 307,  { "Vamp Castle Boss Room 4 - Choices", "vamp", "Vamp Castle" } },
    { 308,  { "Vamp Castle Boss Room 4 - Choices", "vamp", "Vamp Castle" } },
    {  31,  { "Seabed Field 3 - Undersea Park", "ghost", "Ghost Blue Area" } },
    { 310,  { "Beast Garden", "rose", "Rose Garden Area" } },
    { 311,  { "Beast Garden", "rose", "Rose Garden Area" } },
    { 312,  { "Grand Ball Room 5 - Jelly Alert", "unknown", "Unknown Map" } },
    { 313,  { "Grand Ball Room 3 - Cucool Alert", "unknown", "Unknown Map" } },
    { 314,  { "Grand Ball Room - Mask Alert", "unknown", "Unknown Map" } },
    { 315,  { "Grand Ball Room 8 - Snow Lady Alert", "snow", "Snow Hill Area" } },
    { 316,  { "Grand Ball Room 4  - Skull Alert", "unknown", "Unknown Map" } },
    { 317,  { "Grand Ball Room 2 - Sand Alert", "unknown", "Unknown Map" } },
    { 318,  { "Ball Room 2 - Sand Alert", "unknown", "Unknown Map" } },
    { 319,  { "Christmas Garden", "snow", "Snow Hill Area" } },
    {  32,  { "Seabed Field 4 - Undersea Grave", "ghost", "Ghost Blue Area" } },
    { 320,  { "Tapasco Mine - Silent Lava", "mine", "Mines" } },
    { 321,  { "Tapasco Mine 1 - Silent Lava", "mine", "Mines" } },
    { 322,  { "Tapasco Mine 2 - Silent Lava", "mine", "Mines" } },
    { 324,  { "Tower of Chaos Entrance (1st Floor)", "chaos", "Chaos Tower Area" } },
    { 325,  { "Tower of Chaos 2nd Floor", "chaos", "Chaos Tower Area" } },
    { 326,  { "Tower of Chaos 3rd Floor", "chaos", "Chaos Tower Area" } },
    { 327,  { "Tower of Chaos 4th Floor", "chaos", "Chaos Tower Area" } },
    { 328,  { "Tower of Chaos 5th Floor", "chaos", "Chaos Tower Area" } },
    { 329,  { "Tower of Chaos 6th Floor", "chaos", "Chaos Tower Area" } },
    {  33,  { "Beach Town - Paradise", "desert", "Desert Beach Area" } },
    { 330,  { "Tower of Chaos 7th Floor (Safe Floor)", "chaos", "Chaos Tower Area" } },
    { 331,  { "Tower of Chaos 8th Floor", "chaos", "Chaos Tower Area" } },
    { 332,  { "Tower of Chaos 9th Floor", "chaos", "Chaos Tower Area" } },
    { 333,  { "Tower of Chaos 10th Floor", "chaos", "Chaos Tower Area" } },
    { 334,  { "Tower of Chaos 11th Floor", "chaos", "Chaos Tower Area" } },
    { 335,  { "Tower of Chaos 12th Floor", "chaos", "Chaos Tower Area" } },
    { 336,  { "1st Closed Lot of Silent Lava", "mine", "Mines" } },
    { 337,  { "2nd Closed Lot of Silent Lava", "mine", "Mines" } },
    { 338,  { "Trench of the Dead", "ghost", "Ghost Blue Area" } },
    { 339,  { "Trench of Patience", "ghost", "Ghost Blue Area" } },
    {  34,  { "Paradise Shop", "desert", "Desert Beach Area" } },
    { 340,  { "Whirlpool of Agony", "ghost", "Ghost Blue Area" } },
    { 341,  { "Trench of the Pirate", "ghost", "Ghost Blue Area" } },
    { 342,  { "Don Cavalier's Consciousness-Filled World", "unknown", "Unknown Map" } },
    { 343,  { "Phantom Dungeon - 1F Silent Hallway", "phantom", "Phantom School" } },
    { 344,  { "Phantom Dungeon 1-1", "phantom", "Phantom School" } },
    { 345,  { "Phantom Dungeon 1-2", "phantom", "Phantom School" } },
    { 346,  { "Phantom Dungeon 1-3", "phantom", "Phantom School" } },
    { 347,  { "Phantom Dungeon 1-4", "phantom", "Phantom School" } },
    { 348,  { "Phantom Dungeon - 1F Toilet", "phantom", "Phantom School" } },
    { 349,  { "Phantom Dungeon - 2F Chilly Hallway", "phantom", "Phantom School" } },
    {  35,  { "Paradise Monster Guild", "desert", "Desert Beach Area" } },
    { 350,  { "Phantom Dungeon 2-1", "phantom", "Phantom School" } },
    { 351,  { "Phantom Dungeon 2-2", "phantom", "Phantom School" } },
    { 352,  { "Phantom Dungeon 2-3", "phantom", "Phantom School" } },
    { 353,  { "Phantom Dungeon 2-4", "phantom", "Phantom School" } },
    { 354,  { "Phantom Dungeon - 2F Toilet", "phantom", "Phantom School" } },
    { 355,  { "Phantom Dungeon - 3F Shiver Hallway", "phantom", "Phantom School" } },
    { 356,  { "Phantom Dungeon 3-1", "phantom", "Phantom School" } },
    { 357,  { "Phantom Dungeon 3-2", "phantom", "Phantom School" } },
    { 358,  { "Phantom Dungeon 3-3", "phantom", "Phantom School" } },
    { 359,  { "Phantom Dungeon 3-4", "phantom", "Phantom School" } },
    {  36,  { "TBA", "unknown", "Unknown Map" } },
    { 360,  { "Phantom Dungeon - 3F Toilet", "phantom", "Phantom School" } },
    {  37,  { "Beach Field 6 - Statue of Anubis", "desert", "Desert Beach Area" } },
    { 370,  { "Mirage Island Field 4 - Alteo Construction Site", "mirage", "Mirage Island Area" } },
    { 371,  { "Mirage Island Field 5 - Alteo City", "mirage", "Mirage Island Area" } },
    { 372,  { "Mirage Island Field 6 - Water Garden", "mirage", "Mirage Island Area" } },
    { 373,  { "Mirage Island Field 7 - Guardian's Square", "mirage", "Mirage Island Area" } },
    { 374,  { "Nefertiti's Shrine", "mirage", "Mirage Island Area" } },
    { 375,  { "Trickster's Shrine", "mirage", "Mirage Island Area" } },
    { 376,  { "Room of Light", "mirage", "Mirage Island Area" } },
    { 377,  { "Guardian's Room", "mirage", "Mirage Island Area" } },
    { 378,  { "Hologram Chamber", "mirage", "Mirage Island Area" } },
    { 379,  { "Peak of the Dead", "mirage", "Mirage Island Area" } },
    {  38,  { "Paradise Spa", "desert", "Desert Beach Area" } },
    { 380,  { "Tower of Chaos 13th Floor (Safe Floor)", "chaos", "Chaos Tower Area" } },
    { 381,  { "Tower of Chaos 14th Floor", "chaos", "Chaos Tower Area" } },
    { 382,  { "Tower of Chaos 15th Floor", "chaos", "Chaos Tower Area" } },
    { 383,  { "Tower of Chaos 16th Floor", "chaos", "Chaos Tower Area" } },
    { 384,  { "Tower of Chaos 17th Floor", "chaos", "Chaos Tower Area" } },
    { 385,  { "Tower of Chaos 18th Floor", "chaos", "Chaos Tower Area" } },
    { 386,  { "Tower of Chaos 19th Floor (Safe Floor)", "chaos", "Chaos Tower Area" } },
    { 387,  { "Tower of Chaos 20th Floor", "chaos", "Chaos Tower Area" } },
    { 388,  { "Tower of Chaos 21st Floor", "chaos", "Chaos Tower Area" } },
    { 389,  { "Tower of Chaos 22nd Floor", "chaos", "Chaos Tower Area" } },
    {  39,  { "Beach Field 7 - Delta Island", "desert", "Desert Beach Area" } },
    { 390,  { "Tower of Chaos 23rd Floor", "chaos", "Chaos Tower Area" } },
    { 391,  { "Tower of Chaos 24th Floor", "chaos", "Chaos Tower Area" } },
    { 392,  { "Tower of Chaos 25th Floor (Safe Floor)", "chaos", "Chaos Tower Area" } },
    { 393,  { "Tower of Chaos 26th Floor", "chaos", "Chaos Tower Area" } },
    { 394,  { "Swamp Boss Room Gateway 1 - Sky Lotus", "swampdungeon", "Swamp Dungeon" } },
    { 395,  { "Swamp Boss Room Gateway 2 - Lotus Examination Room", "swampdungeon", "Swamp Dungeon" } },
    { 396,  { "Swamp Boss Room Gateway 3 - Maze Jungle", "swampdungeon", "Swamp Dungeon" } },
    { 397,  { "Swamp Boss Room Gateway 3 - Maze Jungle", "swampdungeon", "Swamp Dungeon" } },
    { 398,  { "Swamp Boss Room Gateway 3 - Maze Jungle", "swampdungeon", "Swamp Dungeon" } },
    { 399,  { "Swamp Boss Room Gateway 4 - Grave of the Ancient Hero", "swampdungeon", "Swamp Dungeon" } },
    {   4,  { "Gate of Ghost Blue", "ghost", "Ghost Blue Area" } },
    {  40,  { "Lost Land 4" , "unknown", "Unknown Map" } },
    { 400,  { "Unknown", "unknown", "Unknown Map" } },
    { 401,  { "Tower of Chaos 27th Floor", "chaos", "Chaos Tower Area" } },
    { 402,  { "Tower of Chaos 28th Floor", "chaos", "Chaos Tower Area" } },
    { 403,  { "Tower of Chaos 29th Floor", "chaos", "Chaos Tower Area" } },
    { 404,  { "Tower of Chaos 30th Floor", "chaos", "Chaos Tower Area" } },
    { 405,  { "Tower of Chaos 31st Floor (Safe Floor)", "chaos", "Chaos Tower Area" } },
    { 406,  { "Tower of Chaos 32nd Floor", "chaos", "Chaos Tower Area" } },
    { 407,  { "Tower of Chaos 33rd Floor", "chaos", "Chaos Tower Area" } },
    { 408,  { "Tower of Chaos 34th Floor", "chaos", "Chaos Tower Area" } },
    { 409,  { "Tower of Chaos 35th Floor", "chaos", "Chaos Tower Area" } },
    {  41,  { "Lost Land 5", "unknown", "Unknown Map" } },
    { 410,  { "Tower of Chaos 36th Floor", "chaos", "Chaos Tower Area" } },
    { 411,  { "Tower of Chaos 37th Floor (Safe Floor)", "chaos", "Chaos Tower Area" } },
    { 412,  { "Tower of Chaos 38th Floor", "chaos", "Chaos Tower Area" } },
    { 413,  { "Tower of Chaos 39th Floor", "chaos", "Chaos Tower Area" } },
    { 414,  { "Tower of Chaos 40th Floor", "chaos", "Chaos Tower Area" } },
    { 415,  { "Tower of Chaos 41st Floor", "chaos", "Chaos Tower Area" } },
    { 416,  { "Tower of Chaos 42nd Floor", "chaos", "Chaos Tower Area" } },
    { 417,  { "Tower of Chaos 43rdFloor (Safe Floor)", "chaos", "Chaos Tower Area" } },
    { 418,  { "Tower of Chaos 44th Floor", "chaos", "Chaos Tower Area" } },
    { 419,  { "Tower of Chaos 45th Floor", "chaos", "Chaos Tower Area" } },
    {  42,  { "Relics Field 4 - An Altar for Sacrifice", "cabala", "Caballa Relics Area" } },
    { 420,  { "Tower of Chaos 46th Floor", "chaos", "Chaos Tower Area" } },
    { 421,  { "Tower of Chaos 47th Floor", "chaos", "Chaos Tower Area" } },
    { 422,  { "Tower of Chaos 48th Floor", "chaos", "Chaos Tower Area" } },
    { 423,  { "Tower of Chaos 49th Floor (Safe Floor)", "chaos", "Chaos Tower Area" } },
    { 424,  { "Tower of Chaos 50th Floor", "chaos", "Chaos Tower Area" } },
    { 425,  { "Tower of Chaos 51st Floor", "chaos", "Chaos Tower Area" } },
    { 426,  { "Tower of Chaos 52nd Floor", "chaos", "Chaos Tower Area" } },
    { 427,  { "Tower of Chaos 53rd Floor", "chaos", "Chaos Tower Area" } },
    { 428,  { "Tower of Chaos 54th Floor", "chaos", "Chaos Tower Area" } },
    { 429,  { "Gate of Abyss", "abyss", "Abyss Area" } },
    {  43,  { "Ghost Blue Seabed Town - Aquarius", "ghost", "Ghost Blue Area" } },
    { 430,  { "Abyss Town - Platonia", "abyss", "Abyss Area" } },
    { 431,  { "Abyss Field 1 - The Valley Mouth", "abyss", "Abyss Area" } },
    { 432,  { "Abyss Field 2 - Living Boneyard", "abyss", "Abyss Area" } },
    { 433,  { "Abyss Field 3 - The Dark Hills", "abyss", "Abyss Area" } },
    { 434,  { "Abyss Field 4 - The Crushing Depths", "abyss", "Abyss Area" } },
    { 435,  { "Tower of Chaos 55th Floor (Safe Floor)", "chaos", "Chaos Tower Area" } },
    { 436,  { "Tower of Chaos 56th Floor", "chaos", "Chaos Tower Area" } },
    { 437,  { "Tower of Chaos 57th Floor", "chaos", "Chaos Tower Area" } },
    { 438,  { "Tower of Chaos 58th Floor", "chaos", "Chaos Tower Area" } },
    { 439,  { "Tower of Chaos 59th Floor", "chaos", "Chaos Tower Area" } },
    {  44,  { "Aquarius Inn", "ghost", "Ghost Blue Area" } },
    { 440,  { "Tower of Chaos 60th Floor", "chaos", "Chaos Tower Area" } },
    { 441,  { "Tower of Chaos 61st Floor (Safe Floor)", "chaos", "Chaos Tower Area" } },
    { 442,  { "Tower of Chaos 62nd Floor", "chaos", "Chaos Tower Area" } },
    { 443,  { "Tower of Chaos 63rd Floor", "chaos", "Chaos Tower Area" } },
    { 444,  { "Tower of Chaos 64th Floor", "chaos", "Chaos Tower Area" } },
    { 445,  { "Tower of Chaos 65th Floor", "chaos", "Chaos Tower Area" } },
    { 446,  { "Tower of Chaos 66th Floor", "chaos", "Chaos Tower Area" } },
    { 447,  { "Tower of Chaos 67th Floor (Safe Floor)", "chaos", "Chaos Tower Area" } },
    { 448,  { "Tower of Chaos 68th Floor", "chaos", "Chaos Tower Area" } },
    {  45,  { "Aquarius Monster Guild", "ghost", "Ghost Blue Area" } },
    { 453,  { "Caballa Relics Boss Path 1 - Waking Dream", "cabaladungeon", "Caballa Relics Dungeon" } },
    { 454,  { "Caballa Relics Boss Path 2 - Dread Slumber", "cabaladungeon", "Caballa Relics Dungeon" } },
    { 456,  { "Caballa Relics Boss Path 3 - Rude Awakening", "cabaladungeon", "Caballa Relics Dungeon" } },
    { 457,  { "Path to Oops Wharf Boss 1 - Not this ship", "oops", "Oops Wharf" } },
    { 458,  { "Path to Oops Wharf Boss 1 - Not this ship", "oops", "Oops Wharf" } },
    { 459,  { "Path to Oops Wharf Boss 2 - Not this map", "oops", "Oops Wharf" } },
    {  46,  { "Aquarius Shop", "ghost", "Ghost Blue Area" } },
    { 460,  { "Path to Oops Wharf Boss 3 - Real Wharf of Darkness", "oops", "Oops Wharf" } },
    { 461,  { "Path to Oops Wharf Boss 4 - Real Dock of Darkness", "oops", "Oops Wharf" } },
    { 462,  { "Gate of Black Ash", "ash", "Black Ash Dungeon" } },
    {  47,  { "Paradise OX", "desert", "Desert Beach Area" } },
    { 475,  { "Blue Ice Trial 1 - Gate of Ice Palace", "icedungeon", "Ice Dungeon" } },
    { 476,  { "Blue Ice Trial 2 - Ice Palace Stairs", "icedungeon", "Ice Dungeon" } },
    { 477,  { "Blue Ice Trial 3 - Ice Palace Hallway", "icedungeon", "Ice Dungeon" } },
    { 478,  { "Blue Ice Trial 4 - Ice Palace Maid's Room", "icedungeon", "Ice Dungeon" } },
    { 479,  { "Blue Ice Trial 5 - Ice Palace Jail", "icedungeon", "Ice Dungeon" } },
    {  48,  { "Aquarius Shrine", "ghost", "Ghost Blue Area" } },
    { 480,  { "Blue Ice Trial 5 - Ice Palace Jail", "icedungeon", "Ice Dungeon" } },
    { 481,  { "Blue Ice Trial 5 - Ice Palace Jail", "icedungeon", "Ice Dungeon" } },
    { 487,  { "Underground Dev Room - Underground Passage", "dev", "Underground Dev Area" } },
    { 488,  { "Underground Dev Room - Lobby", "dev", "Underground Dev Area" } },
    { 489,  { "Underground Dev Room - Dev Room", "dev", "Underground Dev Area" } },
    {  49,  { "Swamp Field 4 - Dark Omen", "swamp", "Swamp Area" } },
    { 490,  { "Underground Dev Room - System Control Room", "dev", "Underground Dev Area" } },
    { 491,  { "Techichi Path to Soki 1 - Maze of Death", "ash", "Black Ash Dungeon" } },
    { 492,  { "Techichi Path to Soki 1 - Maze of Death", "ash", "Black Ash Dungeon" } },
    { 493,  { "Techichi Path to Soki 2 - Origin of Death", "ash", "Black Ash Dungeon" } },
    { 494,  { "Techichi Path to Soki 3 - Death's Time", "ash", "Black Ash Dungeon" } },
    { 495,  { "Techichi Path to Soki 4 - Test of Death", "ash", "Black Ash Dungeon" } },
    { 496,  { "Hologram Room", "unknown", "Unknown Map" } },
    { 497,  { "Underground Dev Room - Underground Passage 2", "dev", "Underground Dev Area" } },
    { 498,  { "Underground Dev Room - Underground Passage 3", "dev", "Underground Dev Area" } },
    { 499,  { "Underground Dev Room - Underground Passage 4", "dev", "Underground Dev Area" } },
    {   5,  { "Oops Wharf", "oops", "Oops Wharf" } },
    {  50,  { "Nora Sewer", "nora", "Nora Sewer" } },
    { 501,  { "GM Carbon Headquarters", "dev", "Underground Dev Area" } },
    { 502,  { "Underground Dev Room - Underground Passage 5", "dev", "Underground Dev Area" } },
    { 503,  { "Underground Dev Room - Control Room", "dev", "Underground Dev Area" } },
    { 504,  { "Memory of a Nightmare", "unknown", "Unknown Map" } },
    { 505,  { "Giuvanni's Memory", "unknown", "Unknown Map" }  },
    { 506,  { "Rosaline's Memory", "unknown", "Unknown Map" }  },
    { 507,  { "Cavalier's Office", "dev", "Underground Dev Area" } },
    { 508,  { "Secret Room", "dev", "Underground Dev Area" } },
    { 509,  { "Giuvanni's Hidden Room", "dev", "Underground Dev Area" } },
    {  51,  { "Abyss Dungeon 3", "unknown", "Unknown Map" } },
    { 510,  { "Ocean of the Past", "unknown", "Unknown Map" } },
    { 511,  { "The Sarcophagus", "dev", "Underground Dev Area" } },
    { 512,  { "The Prophecy", "dev", "Underground Dev Area" } },
    { 513,  { "Black Market - Desert Beach", "desert", "Desert Beach Area" } },
    { 514,  { "Black Market - Megalo Forest", "megalo", "Megalopolis Area" } },
    { 515,  { "Black Market - Caballa Relics", "cabala", "Caballa Relics Area" } },
    { 516,  { "Black Market - Oops Wharf", "oops", "Oops Wharf" } },
    { 517,  { "Black Market - Mermaid Palace", "mermaid", "Mermaid Palace Area" } },
    { 518,  { "Black Market - Mirage Island", "mirage", "Mirage Island Area" } },
    { 519,  { "Black Market - Ghost Blue", "ghost", "Ghost Blue Area" } },
    {  52,  { "Abyss Dungeon 4", "unknown", "Unknown Map" } },
    { 520,  { "Black Market - Rose Garden", "rose", "Rose Garden Area" } },
    { 521,  { "Black Market - Black Swamp", "swamp", "Swamp Area" } },
    { 522,  { "Black Market - Underground HQ", "dev", "Underground Dev Area" } },
    { 523,  { "Black Market - Snow Hill", "snow", "Snow Hill Area" } },
    { 524,  { "Black Market - Techichi", "techichi", "Techichi Volcano Area" } },
    { 525,  { "Black Market - Tapasco", "tapasco", "Tapasco Volcano Area" } },
    { 526,  { "Black Market - Abyss", "abyss", "Abyss Area" } },
    { 527,  { "Poppuri Dungeon - Mysterious Space", "poppuri", "Poppuri Dungeon" } },
    { 528,  { "Poppuri Dungeon - Mysterious Space", "poppuri", "Poppuri Dungeon" } },
    { 529,  { "Poppuri Dungeon - Courage Trial", "poppuri", "Poppuri Dungeon" } },
    {  53,  { "Seabed Field 5- Abyss", "ghost", "Ghost Blue Area" } },
    { 530,  { "Poppuri Dungeon - Wisdom Trial", "poppuri", "Poppuri Dungeon" } },
    { 531,  { "Poppuri Dungeon - Dream Trial", "poppuri", "Poppuri Dungeon" } },
    { 532,  { "Poppuri Dungeon - Love Trial", "poppuri", "Poppuri Dungeon" } },
    { 533,  { "Young Rosaline's Room", "unknown", "Unknown Map" }  },
    { 534,  { "Abraxas - Young Rosaline's Room", "unknown", "Unknown Map" } },
    { 535,  { "Eclipse's Dimension", "unknown", "Unknown Map" }  },
    { 536,  { "Eclipse's Dimension", "unknown", "Unknown Map" }  },
    { 537,  { "Another Dimension of Light", "unknown", "Unknown Map" } },
    { 538,  { "Vamp Castle Parlor - Soul Sanctuary", "vamp", "Vamp Castle" } },
    { 539,  { "Black Swamp - Site of Life", "swamp", "Swamp Area" } },
    {  54,  { "Relics Town - Azteca", "cabala", "Caballa Relics Area" } },
    { 540,  { "Rose Garden Park", "rose", "Rose Garden Area" } },
    { 541,  { "Rose Garden Park", "rose", "Rose Garden Area" } },
    { 542,  { "Rose Garden Park", "rose", "Rose Garden Area" } },
    { 543,  { "Janus's Secret Hideaway - Memory of Flames", "unknown", "Unknown Map" }  },
    { 544,  { "Farmer Tsetsech farm 2", "unknown", "Unknown Map" } },
    { 545,  { "Closed Amusement Park - Megalo Land", "megalo", "Megalopolis Area" } },
    { 546,  { "Tsetsech's Rose Garden", "unknown", "Unknown Map" } },
    { 547,  { "廢棄的遊樂場 - 隱密空間", "unknown", "Unknown Map" }  },
    { 548,  { "Closed Amusement Park - Secret Garden", "unknown", "Unknown Map" } },
    { 549,  { "Ghost Blue - Shadow Sanctuary", "ghost", "Ghost Blue Area" } },
    {  55,  { "Azteca Monster Guild", "cabala", "Caballa Relics Area" } },
    { 550,  { "Caballa Relics - Shadow Sanctuary", "cabala", "Caballa Relics Area" } },
    { 551,  { "Black Swamp - Shadow Sanctuary", "swamp", "Swamp Area" } },
    { 552,  { "Oops Wharf - Shadow Sanctuary", "oops", "Oops Wharf" } },
    { 553,  { "Techichi Volcano - Shadow Sanctuary", "techichi", "Techichi Volcano Area" } },
    { 554,  { "Tapasco Volcano - Shadow Sanctuary", "tapasco", "Tapasco Volcano Area" } },
    { 555,  { "Snow Hill - Shadow Sanctuary", "snow", "Snow Hill Area" } },
    { 556,  { "Rose Garden - Shadow Sanctuary", "rose", "Rose Garden Area" } },
    { 557,  { "Wedding Hall", "unknown", "Unknown Map" } },
    { 558,  { "Caballa Hall", "cabala", "Caballa Relics Area" } },
    { 559,  { "Megalo Hall", "megalo", "Megalopolis Area" } },
    {  56,  { "Azteca Sauna", "cabala", "Caballa Relics Area" } },
    { 561,  { "Lovers' Maze", "unknown", "Unknown Map" } },
    { 562,  { "1st Harkon Sanctuary", "unknown", "Unknown Map" } },
    { 563,  { "2nd Harkon Sanctuary", "unknown", "Unknown Map" } },
    { 564,  { "3rd Harkon Sanctuary", "unknown", "Unknown Map" } },
    { 565,  { "Janus' Hidden Refuge", "unknown", "Unknown Map" } },
    { 566,  { "Grand Ball Room 9 - Stone Statue Alert", "unknown", "Unknown Map" } },
    { 567,  { "Ball Room 9 - Stone Statue Alert", "unknown", "Unknown Map" } },
    { 568,  { "Grand Ball Room 10 - Oak Alert", "unknown", "Unknown Map" } },
    { 569,  { "Ball Room 10 - Oak Alert", "unknown", "Unknown Map" } },
    {  57,  { "Caballa Relics Dungeon 1", "cabaladungeon", "Caballa Relics Dungeon" } },
    { 570,  { "Grand Ball Room 1 - Cora Alert", "cora", "Coral Beach Area" } },
    { 571,  { "Ball Room 1 - Cora Alert", "cora", "Coral Beach Area" } },
    { 572,  { "Grand Ball Room 7 - Mud Alert", "unknown", "Unknown Map" } },
    { 573,  { "Ball Room 7 - Mud Alert", "unknown", "Unknown Map" } },
    { 574,  { "Gate of Mermaid Palace", "mermaid", "Mermaid Palace Area" } },
    { 575,  { "Underground Dev Room - Old Storehouse", "dev", "Underground Dev Area" } },
    { 576,  { "Underground Dev Room - Supply Closet", "dev", "Underground Dev Area" } },
    { 578,  { "Mysterious Cave", "unknown", "Unknown Map" }  },
    { 579,  { "Fiesta Waiting Room 1 - Cora Alert", "unknown", "Unknown Map" } },
    {  58,  { "Caballa Relics Dungeon 2", "cabaladungeon", "Caballa Relics Dungeon" } },
    { 580,  { "Fiesta Waiting Room 2 - Sand Alert", "unknown", "Unknown Map" } },
    { 581,  { "Fiesta Waiting Room 3 - Cucool Alert", "unknown", "Unknown Map" } },
    { 582,  { "Fiesta Waiting Room 4 - Skull Alert", "unknown", "Unknown Map" } },
    { 583,  { "Fiesta Waiting Room 5 - Jelly Alert", "unknown", "Unknown Map" } },
    { 584,  { "Fiesta Waiting Room 6 - Mask Alert", "unknown", "Unknown Map" } },
    { 585,  { "Fiesta Waiting Room 7 - Mud Alert", "unknown", "Unknown Map" } },
    { 586,  { "Fiesta Waiting Room 8 - Snow Lady Alert", "unknown", "Unknown Map" } },
    { 587,  { "Fiesta Waiting Room 9 - Stone Statue Alert", "unknown", "Unknown Map" } },
    { 588,  { "Fiesta Waiting Room 10 - Oak Alert", "unknown", "Unknown Map" } },
    { 589,  { "Snow Hill Town - Laplanoel", "snow", "Snow Hill Area" } },
    {  59,  { "Caballa Relics Dungeon 3", "cabaladungeon", "Caballa Relics Dungeon" } },
    { 590,  { "Laplanoel - Santa's Post Office", "snow", "Snow Hill Area" } },
    { 591,  { "Laplanoel Shopping Mall", "snow", "Snow Hill Area" } },
    { 592,  { "Laplanoel Monster Guild", "snow", "Snow Hill Area" } },
    { 593,  { "拉普拉諾技能訓練所", "unknown", "Unknown Map" }  },
    {   6,  { "Gate of Black Swamp", "swamp", "Swamp Area" } },
    {  60,  { "Caballa Relics Dungeon 4", "cabaladungeon", "Caballa Relics Dungeon" } },
    { 605,  { "Gate of Alteo Empire", "alteo", "Alteo Empire Area" } },
    { 606,  { "Tree Sanctuary", "alteo", "Alteo Empire Area" } },
    { 607,  { "Tree Sanctuary", "alteo", "Alteo Empire Area" } },
    { 608,  { "Alteo Empire Field 1 - Secret Garden", "alteo", "Alteo Empire Area" } },
    { 609,  { "Alteo Empire Field 2 - Time Cascade", "alteo", "Alteo Empire Area" } },
    {  61,  { "The Trident Maze", "cabaladungeon", "Caballa Relics Dungeon" } },
    { 610,  { "Alteo Empire Field 3 - Sanctuary Forest", "alteo", "Alteo Empire Area" } },
    { 611,  { "Gate of Nefertiti Shrine", "alteo", "Alteo Empire Area" } },
    { 612,  { "Gate of Nefertiti Shrine", "alteo", "Alteo Empire Area" } },
    { 613,  { "The Shrine's Secret Passage", "alteo", "Alteo Empire Area" } },
    { 614,  { "The Shrine's Secret Passage", "alteo", "Alteo Empire Area" } },
    { 615,  { "Nefertiti's Audience Chamber", "alteo", "Alteo Empire Area" } },
    { 616,  { "Nefertiti's Audience Chamber", "alteo", "Alteo Empire Area" } },
    { 617,  { "Robin's Memory", "unknown", "Unknown Map" }  },
    { 618,  { "Space of Light", "unknown", "Unknown Map" }  },
    { 619,  { "Matrix", "unknown", "Unknown Map" }  },
    {  62,  { "Swamp Field 5 - Further Maze of Forest", "swamp", "Swamp Area" } },
    { 620,  { "Matrix", "unknown", "Unknown Map" }  },
    { 621,  { "Matrix", "unknown", "Unknown Map" }  },
    { 622,  { "Matrix", "unknown", "Unknown Map" }  },
    { 623,  { "Matrix", "unknown", "Unknown Map" }  },
    { 624,  { "Chagan's Heart (Purification)", "unknown", "Unknown Map" }  },
    { 625,  { "Deep Within Chagan's Heart", "unknown", "Unknown Map" }  },
    { 626,  { "Deep Within Chagan's Heart", "unknown", "Unknown Map" }  },
    { 627,  { "Chagan's Heart (Confusion)", "unknown", "Unknown Map" }  },
    {  63,  { "Techichi Field 1", "techichi", "Techichi Volcano Area" } },
    {  64,  { "Techichi Field 2", "techichi", "Techichi Volcano Area" } },
    {  65,  { "Techichi Field 3", "techichi", "Techichi Volcano Area" } },
    {  66,  { "Techichi Field 4", "techichi", "Techichi Volcano Area" } },
    {  67,  { "Techichi - Tango Cabin", "techichi", "Techichi Volcano Area" } },
    {  68,  { "Frost Wind Forest 2", "megalo", "Megalopolis Area" } },
    {  69,  { "Swamp Town - Carbigal", "swamp", "Swamp Area" } },
    {   7,  { "Gate of Tapasco Volcano", "tapasco", "Tapasco Volcano Area" } },
    {  70,  { "Carbigal Shop", "swamp", "Swamp Area" } },
    {  71,  { "Carbigal Monster Guild", "swamp", "Swamp Area" } },
    {  72,  { "Carbigal Tea House", "swamp", "Swamp Area" } },
    {  73,  { "Pyramid Dungeon 1 - Hall of the Slave", "pyramid", "Pyramid Dungeon" } },
    {  74,  { "Pyramid Dungeon 2 - Hall of Harpy", "pyramid", "Pyramid Dungeon" } },
    {  75,  { "Pyramid Dungeon 3 - Hall of Bastet", "pyramid", "Pyramid Dungeon" } },
    {  76,  { "Pyramid Dungeon 4 - Hall of Dead", "pyramid", "Pyramid Dungeon" } },
    {  77,  { "Pyramid Dungeon 5 - Hall of Love Affair", "pyramid", "Pyramid Dungeon" } },
    {  78,  { "Pyramid Dungeon 6 - Hall of the Queen", "pyramid", "Pyramid Dungeon" } },
    {  79,  { "Swamp Field 6 - Lake of Illusion", "swamp", "Swamp Area" } },
    {   8,  { "Relics Field 1 - Atlas", "cabala", "Caballa Relics Area" } },
    {  80,  { "Megalopolis Shop", "megalo", "Megalopolis Area" } },
    {  81,  { "Megalopolis Bank", "megalo", "Megalopolis Area" } },
    {  82,  { "Snow Field 1 - Merry Christmas", "snow", "Snow Hill Area" } },
    {  83,  { "Snow Field 2 - Snowflake Park", "snow", "Snow Hill Area" } },
    {  84,  { "Snow Hill Gift Factory", "snow", "Snow Hill Area" } },
    {  85,  { "Snow Field 3 - Stairway of Snowflake", "snow", "Snow Hill Area" } },
    {  86,  { "Event Garden - Ceremonia", "event", "Event Garden Area" } },
    {  87,  { "Megalopolis Monster Guild", "megalo", "Megalopolis Area" } },
    {  88,  { "Megalopolis Guild Office", "megalo", "Megalopolis Area" } },
    {  89,  { "Rose Field 1 - Stairway to Sorrow", "rose", "Rose Garden Area" } },
    {   9,  { "Desert Beach Field 1 - Delta Island", "desert", "Desert Beach Area" } },
    {  90,  { "Rose Field 2 - Maze of Black Rose", "rose", "Rose Garden Area" } },
    {  91,  { "Rose Field 3 - Maze of Blue Rose", "rose", "Rose Garden Area" } },
    {  92,  { "Rose Field 4 - Bloom Grave", "rose", "Rose Garden Area" } },
    {  93,  { "Secret Garden of Rosetta", "rose", "Rose Garden Area" } },
    {  94,  { "Ice Dungeon 1 - Cave of Darkblue", "icedungeon", "Ice Dungeon" } },
    {  95,  { "Ice Dungeon 2 - Cave of Crystal", "icedungeon", "Ice Dungeon" } },
    {  96,  { "Ice Dungeon 3 - Heart of Crystal", "icedungeon", "Ice Dungeon" } },
    {  97,  { "Ice Dungeon 4 - Teardrop walkways", "icedungeon", "Ice Dungeon" } },
    {  98,  { "Snow Field 4 - Happy New Year", "snow", "Snow Hill Area" } },
    {  99,  { "Path to Snow Hill", "snow", "Snow Hill Area" } }
};

/*──────────────────────── helper functions ──────────────────────────*/

bool GetMapName(int id, std::string& outName)
{
    auto it = g_MapName.find(id);
    if (it == g_MapName.end()) return false;
    outName = it->second.name;          //  ← FIX
    return true;
}

// default key:  lower-case map name, spaces → underscores
bool GetMapAsset(int id, std::string& outKey)
{
    std::string name;
    if (!GetMapName(id, name)) return false;

    std::transform(name.begin(), name.end(), name.begin(),
        [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

    std::replace(name.begin(), name.end(), ' ', '_');
    outKey = name;
    return true;
}

bool GetMapInfo(int id, std::string& asset, std::string& tip)
{
    auto it = g_MapName.find(id);
    if (it == g_MapName.end()) return false;
    asset = it->second.asset;
    tip = it->second.tip;
    return true;
}

